import type { NavItem, Product, Demand, CompanyProfile, Solution } from '@/types';

export const NAV_ITEMS: NavItem[] = [
  { id: 'home', label: '首页', href: '/' },
  { id: 'featured', label: '精选', href: '/featured' },
  { id: 'products', label: 'AI产品', href: '/products' },
  { id: 'agents', label: 'AI Agent', href: '/agents' },
  { id: 'companies', label: 'AI公司', href: '/companies' },
  { id: 'demands', label: '需求大厅', href: '/demands' },
  { id: 'solutions', label: '解决方案', href: '/solutions' },
  { id: 'developers', label: 'API', href: '/developers' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1', name: '智问企业知识库', company: '星河智能科技',
    summary: '面向企业内部文档的私有化知识库问答系统，支持权限控制与答案溯源。',
    description: '', category: 'AI Knowledge Base',
    industryTags: ['manufacturing', 'government', 'research', 'education'],
    capabilityTags: ['RAG', '私有化', '溯源'],
    deploymentModes: ['saas', 'private_cloud', 'on_premise'],
    pricingModel: 'per_project', price: '按项目报价', supportPoc: true,
    supportPrivateDeployment: true, score: '4.8分', rating: 4.8,
    caseCount: 36, pocCount: 12, status: 'published',
    tags: ['RAG', '私有化', '溯源'], deploy: 'SaaS/本地', accent: 'blue', shot: 'knowledge',
    createdAt: '2025-01-15',
  },
  {
    id: 'p2', name: '销售线索Agent', company: '云脉AI',
    summary: '自动搜索市场线索、生成客户画像、跟进建议和邮件草稿。',
    description: '', category: 'AI Agent',
    industryTags: ['retail', 'finance'],
    capabilityTags: ['Agent', 'CRM', '自动化'],
    deploymentModes: ['saas'], pricingModel: 'subscription',
    price: '订阅+服务', supportPoc: false, supportPrivateDeployment: false,
    score: '4.7分', rating: 4.7, caseCount: 24, pocCount: 6,
    status: 'published', tags: ['Agent', 'CRM', '自动化'],
    deploy: 'SaaS/API', accent: 'violet', shot: 'sales', createdAt: '2025-02-01',
  },
  {
    id: 'p3', name: '文档审查助手', company: '蓝鲸智能',
    summary: '支持合同、制度、投标文件的风险识别、条款提取和修订建议。',
    description: '', category: 'Document AI',
    industryTags: ['government', 'finance', 'manufacturing'],
    capabilityTags: ['文档AI', '合规', '审查'],
    deploymentModes: ['private_cloud'], pricingModel: 'subscription',
    price: '年费制', supportPoc: true, supportPrivateDeployment: true,
    score: '4.6分', rating: 4.6, caseCount: 18, pocCount: 8,
    status: 'published', tags: ['文档AI', '合规', '审查'],
    deploy: '私有云', accent: 'cyan', shot: 'review', createdAt: '2025-02-10',
  },
  {
    id: 'p4', name: '客服智能体', company: '言犀科技',
    summary: '面向售前售后场景的多渠道智能客服，支持知识库和工单联动。',
    description: '', category: 'Customer Service',
    industryTags: ['retail', 'education'],
    capabilityTags: ['客服', '多渠道', '工单'],
    deploymentModes: ['saas'], pricingModel: 'per_seat',
    price: '按席位', supportPoc: true, supportPrivateDeployment: false,
    score: '4.7分', rating: 4.7, caseCount: 42, pocCount: 15,
    status: 'published', tags: ['客服', '多渠道', '工单'],
    deploy: 'SaaS', accent: 'green', shot: 'support', createdAt: '2025-03-01',
  },
  {
    id: 'p5', name: '工业视觉检测AI', company: '工识智能',
    summary: '缺陷检测、产线质检与异常告警，支持边缘部署和模型迭代。',
    description: '', category: 'Industrial AI',
    industryTags: ['manufacturing'],
    capabilityTags: ['工业AI', '视觉', '边缘'],
    deploymentModes: ['on_premise'], pricingModel: 'per_project',
    price: '项目制', supportPoc: true, supportPrivateDeployment: true,
    score: '4.5分', rating: 4.5, caseCount: 14, pocCount: 9,
    status: 'published', tags: ['工业AI', '视觉', '边缘'],
    deploy: '本地化', accent: 'orange', shot: 'vision', createdAt: '2025-03-15',
  },
  {
    id: 'p6', name: '科研情报Agent', company: '睿研智能',
    summary: '自动追踪论文、专利、政策和产业动态，生成趋势分析报告。',
    description: '', category: 'Research AI',
    industryTags: ['research'],
    capabilityTags: ['科研', '情报', '报告'],
    deploymentModes: ['saas'], pricingModel: 'subscription',
    price: '订阅制', supportPoc: false, supportPrivateDeployment: false,
    score: '4.6分', rating: 4.6, caseCount: 20, pocCount: 4,
    status: 'published', tags: ['科研', '情报', '报告'],
    deploy: 'SaaS/API', accent: 'slate', shot: 'research', createdAt: '2025-04-01',
  },
  {
    id: 'p7', name: '数据分析Copilot', company: '数澜AI',
    summary: '用自然语言分析业务数据，自动生成图表、洞察和管理报告。',
    description: '', category: 'BI AI',
    industryTags: ['finance', 'retail'],
    capabilityTags: ['BI', 'Copilot', '报表'],
    deploymentModes: ['private_cloud'], pricingModel: 'per_project',
    price: '按项目', supportPoc: true, supportPrivateDeployment: true,
    score: '4.5分', rating: 4.5, caseCount: 16, pocCount: 7,
    status: 'published', tags: ['BI', 'Copilot', '报表'],
    deploy: '私有云', accent: 'blue', shot: 'data', createdAt: '2025-04-10',
  },
  {
    id: 'p8', name: 'AI办公助手', company: '微曜科技',
    summary: '会议纪要、周报生成、制度问答和办公流程自动化助手。',
    description: '', category: 'Office AI',
    industryTags: ['government', 'education'],
    capabilityTags: ['办公', '流程', '总结'],
    deploymentModes: ['saas'], pricingModel: 'per_seat',
    price: '按用户', supportPoc: false, supportPrivateDeployment: false,
    score: '4.4分', rating: 4.4, caseCount: 28, pocCount: 3,
    status: 'published', tags: ['办公', '流程', '总结'],
    deploy: 'SaaS', accent: 'violet', shot: 'office', createdAt: '2025-05-01',
  },
  {
    id: 'p9', name: '代码审查Agent', company: '码观智能',
    summary: '结合仓库规范和研发流程，自动审查代码、需求文档和测试用例。',
    description: '', category: 'Dev AI',
    industryTags: ['industrial_software'],
    capabilityTags: ['研发', 'Agent', '审查'],
    deploymentModes: ['on_premise'], pricingModel: 'subscription',
    price: '年费制', supportPoc: true, supportPrivateDeployment: true,
    score: '4.6分', rating: 4.6, caseCount: 22, pocCount: 10,
    status: 'published', tags: ['研发', 'Agent', '审查'],
    deploy: '私有化', accent: 'green', shot: 'code', createdAt: '2025-05-15',
  },
];

export const DEMANDS: Demand[] = [
  {
    id: 'd1', title: '某制造企业需要建设内部制度知识库问答系统',
    industry: '制造业', budgetRange: '10-30万', deliveryPeriod: '1个月内',
    dataTypes: ['Word', 'PDF', 'Excel'], deploymentRequirement: '私有云',
    description: '', painPoints: '', existingSystems: '',
    supportPoc: true, allowAiSupplier: true,
    matchScore: '92%', matchScoreNum: 0.92, status: 'awaiting_quote', createdAt: '2025-06-01',
  },
  {
    id: 'd2', title: '科研院所需要自动生成航空技术趋势分析报告',
    industry: '科研机构', budgetRange: '30-80万', deliveryPeriod: '1个月内',
    dataTypes: ['PDF', '网页', '数据库'], deploymentRequirement: 'SaaS',
    description: '', painPoints: '', existingSystems: '',
    supportPoc: true, allowAiSupplier: true,
    matchScore: '88%', matchScoreNum: 0.88, status: 'collecting_proposals', createdAt: '2025-06-02',
  },
  {
    id: 'd3', title: '教育集团希望搭建招生客服与内容生成AI助手',
    industry: '教育', budgetRange: '5-20万', deliveryPeriod: '1个月内',
    dataTypes: ['Word', '图片'], deploymentRequirement: 'SaaS',
    description: '', painPoints: '', existingSystems: '',
    supportPoc: false, allowAiSupplier: true,
    matchScore: '76%', matchScoreNum: 0.76, status: 'awaiting_quote', createdAt: '2025-06-03',
  },
  {
    id: 'd4', title: '工业软件团队需要代码审查与需求文档生成Agent',
    industry: '工业软件', budgetRange: '20-50万', deliveryPeriod: '3个月内',
    dataTypes: ['代码仓库', '文档'], deploymentRequirement: '私有化',
    description: '', painPoints: '', existingSystems: '',
    supportPoc: true, allowAiSupplier: true,
    matchScore: '95%', matchScoreNum: 0.95, status: 'collecting_proposals', createdAt: '2025-06-04',
  },
];

export const COMPANIES: CompanyProfile[] = [
  {
    id: 'c1', name: '启元AI', slogan: '企业知识库、Agent开发与本地化部署服务商。',
    description: '专注企业知识库、Agent编排与本地化部署服务。',
    certifications: ['平台认证', 'ISO27001'], capabilities: ['Agent开发', '知识库', '本地部署'],
    industryExperience: ['manufacturing', 'government'],
    deliveryScope: ['企业知识库搭建', 'Agent编排与集成', '私有化部署', 'POC快速验证'],
    caseStudies: ['制造业制度问答', '政务知识库助手', '研发文档审查', '客服知识库升级'],
    rating: 4.8, responseRate: 95, certified: true,
    tags: ['Agent开发', '知识库', '本地部署'],
  },
  {
    id: 'c2', name: '星河智能科技', slogan: '拥有知识库产品和制造业案例，支持 POC 与私有化交付。',
    description: '拥有知识库产品和制造业案例，支持 POC 与私有化交付。',
    certifications: ['平台认证'], capabilities: ['RAG', '制造业', '私有云'],
    industryExperience: ['manufacturing', 'research'],
    deliveryScope: ['私有化RAG问答', '权限控制', '答案溯源', 'OA集成'],
    caseStudies: ['某制造业制度问答系统', '某科研机构知识库'],
    rating: 4.7, responseRate: 92, certified: true,
    tags: ['RAG', '制造业', '私有云'],
  },
  {
    id: 'c3', name: '工识智能', slogan: '围绕制造质检、工艺审查、工业软件 AI 助手提供端到端方案。',
    description: '围绕制造质检、工艺审查、工业软件 AI 助手提供端到端方案。',
    certifications: ['平台认证', 'CE认证'], capabilities: ['工业AI', '视觉检测', '边缘部署'],
    industryExperience: ['manufacturing'],
    deliveryScope: ['缺陷检测', '产线质检', '异常告警', '边缘部署'],
    caseStudies: ['某汽车产线视觉检测', '某钢铁集团工艺审查'],
    rating: 4.6, responseRate: 88, certified: true,
    tags: ['工业AI', '视觉检测', '边缘部署'],
  },
];

export const SOLUTIONS: Solution[] = [
  {
    id: 's1', title: '制造业知识库与工艺问答方案',
    summary: '把制度、工艺、维修手册转为可信问答与溯源系统。',
    description: '', industry: ['manufacturing'], scenario: '制造业知识管理',
    budgetRange: '10-50万', deploymentModes: ['private_cloud', 'on_premise'],
    deliveryPeriod: '4-8周', supportPoc: true,
    components: ['知识库引擎', '文档解析', '问答界面', '权限管理'],
    recommendedProducts: ['p1'], recommendedCompanies: ['c1', 'c2'],
  },
  {
    id: 's2', title: '金融投研情报自动化方案',
    summary: '汇聚研报、公告和新闻，生成可追踪的投资研究摘要。',
    description: '', industry: ['finance'], scenario: '金融投研',
    budgetRange: '30-100万', deploymentModes: ['private_cloud'],
    deliveryPeriod: '6-12周', supportPoc: true,
    components: ['情报采集', 'NLP分析', '报告生成', '知识图谱'],
    recommendedProducts: ['p6'], recommendedCompanies: ['c2'],
  },
  {
    id: 's3', title: '政企热线智能客服方案',
    summary: '建设多渠道客服知识库、工单联动和质检分析闭环。',
    description: '', industry: ['government'], scenario: '政企客服',
    budgetRange: '20-60万', deploymentModes: ['saas', 'private_cloud'],
    deliveryPeriod: '4-8周', supportPoc: true,
    components: ['客服机器人', '工单系统', '质检分析', '知识库'],
    recommendedProducts: ['p4'], recommendedCompanies: ['c1'],
  },
  {
    id: 's4', title: '软件研发 Agent 协作方案',
    summary: '覆盖需求澄清、代码审查、测试生成和交付文档。',
    description: '', industry: ['industrial_software'], scenario: '研发效率',
    budgetRange: '20-50万', deploymentModes: ['on_premise'],
    deliveryPeriod: '6-10周', supportPoc: true,
    components: ['代码审查Agent', '需求分析Agent', '测试生成', '文档助手'],
    recommendedProducts: ['p9'], recommendedCompanies: ['c3'],
  },
];

export const POC_STEPS = [
  { label: '提交需求', desc: '平台记录节点状态、资料与沟通内容。' },
  { label: '上传样例数据', desc: '平台记录节点状态、资料与沟通内容。' },
  { label: '供应商确认', desc: '平台记录节点状态、资料与沟通内容。' },
  { label: 'POC验证', desc: '平台记录节点状态、资料与沟通内容。' },
  { label: '验收评分', desc: '平台记录节点状态、资料与沟通内容。' },
  { label: '进入报价', desc: '平台记录节点状态、资料与沟通内容。' },
];

export const CAPABILITY_CATEGORIES = [
  '知识库问答', 'AI客服', 'AI办公', '数据分析', 'OCR', 'Agent平台', '工业AI', '科研情报',
];
